# Generated by Django 5.2.5 on 2025-10-17 14:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0015_policy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Политика конфиденциальности', 'verbose_name_plural': 'Политики'},
        ),
        migrations.RemoveField(
            model_name='policy',
            name='title',
        ),
        migrations.AlterField(
            model_name='policy',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Основной текст политики (HTML).'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='slug',
            field=models.SlugField(blank=True, help_text='Автогенерируется при сохранении (можно оставить пустым).', max_length=200, null=True, unique=True),
        ),
    ]
