# Generated by Django 5.2.5 on 2025-10-17 15:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0016_alter_policy_options_remove_policy_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Основной текст политики (HTML).'),
        ),
    ]
