# Generated by Django 5.2.5 on 2025-10-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0017_alter_policy_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Политика конфиденциальности', 'verbose_name_plural': 'Политика конфиденциальности'},
        ),
        migrations.RemoveField(
            model_name='policy',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='slug',
        ),
    ]
