# Generated by Django 5.2.5 on 2025-10-17 15:43

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0018_alter_policy_options_remove_policy_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='title',
            field=models.CharField(default='Политика конфиденциальности', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Основной текст'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
